<div id="borrowingReport1">
    <h1>器材借用統計報表</h1>
    <div>
        <table class="table" id="borrowingReport1Table">
            <thead>
                <tr>
                    <th>器材名稱</th>
                    <th>庫存數</th>
                    <th>毀損數量</th>
                    <th>借用數量</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>