<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="author" content="carollai"> 
<meta name="keywords" content="carollai">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>web title</title>
    <!-- Bootstrap -->
    <link href="assets/css/vonder/bootstrap.min.css" rel="stylesheet">
    <!--link href="assets/css/vonder/toggle.switch.css" rel="stylesheet"-->
    <link href="assets/css/vonder/bootstrap-datepicker3.css" rel="stylesheet">
    <link href="assets/css/vonder/bootstrap-editable.css" rel="stylesheet">
    <link href="assets/css/vonder/bootstrap-switch.css" rel="stylesheet">
    <link href="assets/css/vonder/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="assets/css/vonder/select2.css" media="all" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="assets/css/vonder/bootstrap-wysihtml5-0.0.3.css" rel="stylesheet">    

    <link href="assets/css/main.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="javascripts/html5shiv.min.js"></script>
      <script src="javascripts/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <section>
        <!-- Static navbar -->
        <nav class="navbar navbar-default narbar-layout">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="index">應用軟體設計競賽--器材借用</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/borrowing">所有器材借用列表</a></li>
                        <li><a href="/queryborrowing">器材借用查詢</a></li>
                        <li><a href="/report1">器材借用統計報表</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
        </nav>
        <!-- content -->
        <?php echo $this->content(); ?>
    </section>
    
    <!-- Scripts -->
    
    <!-- Scripts -->
    <script src="assets/js/vonder/jquery.js"></script>
    <!-- piexif.min.js is only needed if you wish to resize images before upload to restore exif data.
         This must be loaded before fileinput.min.js -->
    <script src="assets/js/vonder/bootstrap-fileinput/plugins/piexif.min.js" type="text/javascript"></script>
    <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
         This must be loaded before fileinput.min.js -->
    <script src="assets/js/vonder/bootstrap-fileinput/plugins/sortable.min.js" type="text/javascript"></script>
    <!-- purify.min.js is only needed if you wish to purify HTML content in your preview for HTML files.
         This must be loaded before fileinput.min.js -->
    <script src="assets/js/vonder/bootstrap-fileinput/plugins/purify.min.js" type="text/javascript"></script>
    <!-- the main fileinput plugin file -->
    <script src="assets/js/vonder/bootstrap-fileinput/fileinput.min.js"></script>
    <!-- bootstrap.js below is needed if you wish to zoom and view file content 
         in a larger detailed modal dialog -->
    <script src="assets/js/vonder/bootstrap.min.js"></script>
    <script src="assets/js/vonder/moment.js"></script>
    <script src="assets/js/vonder/combodate.js"></script>
    <script src="assets/js/vonder/bootstrap-editable.js"></script>
    <script src="assets/js/vonder/wysihtml5-0.3.0.min.js"></script>
    <script src="assets/js/vonder/bootstrap-wysihtml5-0.0.3.min.js"></script>
    <script src="assets/js/vonder/wysihtml5-0.0.3.js"></script>
    <script src="assets/js/vonder/bootstrap-switch.js"></script>
    <script src="assets/js/vonder/bootstrap-tooltip.js"></script>
    <script src="assets/js/vonder/bootstrap-popover.js"></script>
    <script src="assets/js/vonder/select2.js"></script>
    <!--script src="ckeditor/ckeditor.js"></script-->
    <!--script src="assets/js/vonder/jquery.validity.min.js"></script-->
    <!--script src="assets/js/vonder/vue.min.js"></script-->
    <script src="assets/js/vonder/vue.js"></script>
    <script src="assets/js/index.js"></script>
    
</body>
</html>